name: Deploy to Firebase Hosting on merge

"on":
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install

      - run: yarn build
        env:
          SENTRY_ORG: foudroyer
          SENTRY_PROJECT: front-end
          NODE_OPTIONS: "--max-old-space-size=8192"

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_FOUDROYER_COM }}"
          channelId: live
          projectId: foudroyer-com
